### ISSUE TITLE
Non-ascii author names

### ISSUE THREAD

**Issue by LPardue** [cabo/kramdown-rfc2629#153]
I was curious if the author section could support non-Ascii names (not contact names as documented at `https://github.com/cabo/kramdown-rfc2629/wiki/Syntax#-syntax-contact-names`). Is there some magic incantation I am missing?

If I test `name: Jürgen Möllemann`, everything is ok and I see the name rendered in Author's Addresses section.

If I test `name: トヨタ自動車株式会社` and run kramdown-rfc-2629 if produces 

```
<author initials="T." surname="Jidosha" fullname="トヨタ自動車株式会社">
```

Feeding that to xml2rfc, I see the error 

```
Error: Expected an asciiFullname= attribute to match the unicode fullname value
Not creating output file due to errors (see above)`
```

if I manually modify the XML file to be

```
<author initials="T." surname="Jidosha" fullname="トヨタ自動車株式会社" asciiFullname="Toyota Jidosha">
```

then xml2rfc is happy and it generates an Author's Addresses section like

```
Authors' Addresses

   Toyota Jidosha
   ACME Corp

   Email: toyota@acme.example.com

   Additional contact information:

      トヨタ自動車株式会社
      ACME Corp
```

**Comment by cabo** [comment]
Yes, I always wanted to find a general solution to specifying the ASCII twins to  many attributes, including:

``` 
author[asciiFullname]
author[asciiInitials]
author[asciiSurname]
contact[asciiFullname]
contact[asciiInitials]
contact[asciiSurname]
email[ascii]
organization[asciiAbbrev]
seriesInfo[asciiName]
seriesInfo[asciiValue]
u[ascii]
``` 

leaking less of the ad-hocness of RFCXMLv3 to the user.
If you need it, I'll cook something up.

**Comment by LPardue** [comment]
Thanks for the response. I was curious but this is not urgent for my own needs. I'd be happy to retest changes if you get around to it.

**Comment by LPardue** [comment]
Actually, I thought about this some more and I think it would be really nice to get fixed up if we could. Accomodating these characters in the Author details section is nice but it would be cool if the front page also worked. In my local experimentation, I've struggled to handcrank the XML that would produce something like the examples in Section 3.2 of  https://www.rfc-editor.org/rfc/rfc7997.pdf. But with enough trial and error the following <author> tag generates the sort of output I would expect

```
<author initials="" asciiInitials="T." surname="トヨタ自動車株式会社" asciiSurname="Ishida" fullname="トヨタ自動車株式会社" asciiFullname="Toyota Ishida">
      <organization>ACME inc</organization>
      <address>
        <email>ishida@acme.example.com</email>
      </address>
    </author>
```

```
NWWG                                    トヨタ自動車株式会社 (T. Ishida)
Internet-Draft                                                  ACME inc
Intended status: Standards Track                               L. Pardue
Expires: 30 July 2022                                       TestingStuff
                                                         26 January 2022
```

although I can't really explain why the top-line alignment is off by a few spaces.

I'm sure there is someway to make this work properly. But the important thing with the initials part is that the non-ASCII version is not split by any space characters.

**Comment by cabo** [comment]
On 26. Jan 2022, at 01:47, Lucas Pardue ***@***.***> wrote:
> 
> <author initials="" asciiInitials="T." surname="トヨタ自動車株式会社" asciiSurname="Ishida" fullname="トヨタ自動車株式会社" asciiFullname="Toyota Ishida”>

Do you really need initials/surname here?

Interestingly, kramdown-rfc does have “orgascii” to solve the problem with this part:

>       <organization>ACME inc</organization>

Grüße, Carsten

**Comment by LPardue** [comment]
I'm not sure I understand the question. If we want the author information on the front page to contain non-ASCII characters, aren't these fields required?

**Comment by cabo** [comment]
Well, yes, they probably are (I didn't try).

What I'm really looking at right now is a way to handle the 23 "ascii..." attributes in the v3 grammar in a consistent way, possibly more consistent than the grammar itself...

**Comment by LPardue** [comment]
Understood. I'm far from an expert in this area. All I can say is that for the desired output, by brute force I found one combination of fields that worked. The notable outcome being that, in this example, the `initials` and `asciiInitials` seemed to need to be different - the assumption that there is a first and last name split by a space, and that names can be abbreviated with a `.`, does not hold.

**Comment by cabo** [comment]
I think I have mostly nailed this now.

Unfortunately, xml2rfc doesn't quite play along, 

https://trac.ietf.org/trac/xml2rfc/ticket/707
https://trac.ietf.org/trac/xml2rfc/ticket/708

So I cannot really test all the combinations I'm interested in.

I plan to push a version, but usability may be a bit limited by this.

**Comment by LPardue** [comment]
Thank you @cabo . For the dense people like me, what should the markdown source look like to drive the updated kreamdown-rfc2629? I.e. does it require additional fields or different values in existing fields?

**Comment by cabo** [comment]
Hi Lucas, I'm in the process of writing the announcement for 1.5.26 to the rfc-markdown@ietf.org list.

The actual ascii attributes are partially broken in xml2rfc, so the results of using the new features may be a bit disappointing.

The main feature is that the postal attributes (street etc.) and name: now allow for Latin-1 (incorrectly called "ASCII") alternatives.

So you can write something like:

``` 
    name:
      :: 水⽔arsten ormann
      ascii: Carsten Bormann
    email: cabo@tzi.org
    org:
      :: 🦄
      ascii: ignoredunicorn
      showonfrontpage: true
    street:
      - :: トヨタ自動車株式会社
        ascii: ignoredtoyota1
      - :: トヨタ
        ascii: ignoredtoyota2
    email:
      :: cabo@tzi.org
      ascii: cabo@tzi.org
“`

So where a string would normally occur, there is a hash with `:` and `ascii` as keys.
Some of the values of the example contain the word "ignored" -- this is when xml2rfc often ignores the value due to the current bugs.  As you can see, attributes such as showOnFrontPage [sic] can also be set from these hashes.

So your example would now probably look like:

``` 
  - name:
      :: トヨタ自動車株式会社
      ascii: Toyota Ishida
    org: foo
```

(where the "foo" could also be split into a non-Latin and a Latin part).
Using "name" makes kramdown-rfc do the initials dance, see my Rfc-markdown posting soon.
