### ISSUE TITLE
XML generated for absent date is rejected by xml2rfc --v3

### ISSUE THREAD

**Issue by jyasskin** [cabo/kramdown-rfc2629#64]
I have the following informative reference in my markdown file:

```yaml
informative:
  ServiceWorkers:
    target: https://w3c.github.io/ServiceWorker/
    title: "Service Workers Nightly"
    seriesinfo:
      W3C: "ED"
```

It's missing a `date` entry, so kramdown-rfc2629 generates `<date year="n.d."/>` in the XML. When I configure [i-d-template](https://github.com/martinthomson/i-d-template/) with `XML2RFCV3=true` to use `xml2rfc --v3`, I get the error:

```
Error: Expected <date> attribute "year" to be an integer, but found "n.d."
```

https://tools.ietf.org/html/rfc7991#section-2.17 and https://tools.ietf.org/html/draft-iab-xml2rfc-v3-bis-00#section-2.17 say prose text is expected to be supported, so maybe kramdown-rfc2629 is doing the right thing, but https://tools.ietf.org/html/draft-levkowetz-xml2rfc-v3-implementation-notes-10#section-4.1.3.2 claims prose text in the `year` attribute is unworkable and suggests it be in the content instead.

Maybe kramdown-rfc2629 should emit its own error for an absent year.
