### ISSUE TITLE
not clear how to set the tocDepth attribute

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc2629#99]
[The tocDepth attribute](https://tools.ietf.org/html/rfc7991#section-2.45.14) changes the default depth of the generated table of contents.

It's not clear to me how to get a markdown-sourced document to emit this attribute in a way that `xml2rfc` will respect it.

This came up in the OpenPGP WG's attempt to refresh the cryptographic standards for OpenPGP.  See [Derek Atkins message](https://mailarchive.ietf.org/arch/msg/openpgp/1b_fJlpHpioO1YOJnCyx2kayyIM/) which says:

> The ToC doesn't include anything beyond x.y.z

This isn't urgent, but insofar as we're looking at revisions to [RFC 4880](https://tools.ietf.org/html/rfc4880) it'd be nice to be able to compare the document structure by seeing the same level of ToC depth (RFC 4880 has a ToC 4 levels deep).

**Comment by cabo** [comment]
Here is an example of YAML that does this:

```
...
ipr: trust200902
area: Internet
# wg: CoRE Working Group
kw: Internet-Draft
cat: info

pi:
  toc: yes
  tocdepth: 4
  sortrefs: yes
  symrefs: yes

author:
      -
        name: Carsten Bormann
...
```

Note that this looks like a PI (processing instruction), because that was the way this was done in RFCXMLv2 and kramdown-rfc is trying to be stable.
